backend:
  name: github
  repo: darzouras/darzouras-gridsome-site

media_folder: "static/img"
site_url: https://www.darzouras.com

collections:
  - name: "pages"
    label: "Page"
    folder: "pages"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Permalink"
        name: "permalink"
        widget: "string"
      - label: "Layout"
        name: "layout"
        widget: "select"
        options:
          - label: "Page"
            value: "layouts/page.njk"
          - label: "Home"
            value: "layouts/home.njk"
          - label: "Blog"
            value: "layouts/blog.njk"
        default: "layouts/page.njk"
      - label: "Summary"
        name: "summary"
        widget: "text"
      - label: "Header image"
        name: "header"
        widget: "image"
        default: "/static/img/sailormoonattitude1.PNG"
      - label: "Body"
        name: "body"
        widget: "markdown"
  - name: "blog"
    label: "Blog"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Summary"
        name: "summary"
        widget: "text"
      - label: "Header image"
        name: "header"
        widget: "image"
        default: "/static/img/sailormoonattitude1.PNG"
      - label: "Body"
        name: "body"
        widget: "markdown"
